In [1]:
import numpy as np

**Criação de Array**

In [3]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Array de Zeros

In [4]:
zero_array = np.zeros(shape = (5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [5]:
um_array = np.ones((2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
vazio = np.empty((4,3))
print(vazio)

[[6.92631068e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [11]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr = np.arange(50,200,30)
print(arr)

[ 50  80 110 140 170]


In [14]:
array_linear = np.linspace(0,100, num = 40, endpoint = True)
print(array_linear)

[  0.           2.56410256   5.12820513   7.69230769  10.25641026
  12.82051282  15.38461538  17.94871795  20.51282051  23.07692308
  25.64102564  28.20512821  30.76923077  33.33333333  35.8974359
  38.46153846  41.02564103  43.58974359  46.15384615  48.71794872
  51.28205128  53.84615385  56.41025641  58.97435897  61.53846154
  64.1025641   66.66666667  69.23076923  71.79487179  74.35897436
  76.92307692  79.48717949  82.05128205  84.61538462  87.17948718
  89.74358974  92.30769231  94.87179487  97.43589744 100.        ]


In [15]:
array_linear = np.linspace(0,100, num = 40, endpoint = False)
print(array_linear)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5 50.  52.5 55.  57.5 60.  62.5 65.  67.5
 70.  72.5 75.  77.5 80.  82.5 85.  87.5 90.  92.5 95.  97.5]


In [17]:
array_linear = np.linspace(0,100, num = 40, retstep = True)
print(array_linear)

(array([  0.        ,   2.56410256,   5.12820513,   7.69230769,
        10.25641026,  12.82051282,  15.38461538,  17.94871795,
        20.51282051,  23.07692308,  25.64102564,  28.20512821,
        30.76923077,  33.33333333,  35.8974359 ,  38.46153846,
        41.02564103,  43.58974359,  46.15384615,  48.71794872,
        51.28205128,  53.84615385,  56.41025641,  58.97435897,
        61.53846154,  64.1025641 ,  66.66666667,  69.23076923,
        71.79487179,  74.35897436,  76.92307692,  79.48717949,
        82.05128205,  84.61538462,  87.17948718,  89.74358974,
        92.30769231,  94.87179487,  97.43589744, 100.        ]), np.float64(2.5641025641025643))


**Tamanho Array**

In [46]:
zero_array = np.zeros(shape = (5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


**Transformando Array de 1D em 2D**

In [48]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [49]:
a2 = a[np.newaxis,:]
print(a2.shape)
print(a2.ndim)
print(a2)

(1, 3)
2
[[1 2 3]]


In [50]:
a22 = a[:,np.newaxis]
print(a22.shape)
print(a22.ndim)
print(a22)

(3, 1)
2
[[1]
 [2]
 [3]]


In [51]:
print(a22[0][0])

1
